USE [SQLSourceControl]
GO

/****** Object:  Table [dbo].[SVC_LU_ServerRole]    Script Date: 2017/02/14 07:54:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SVC_LU_ServerRole](
	[ServerRoleID] [int] IDENTITY(1,1) NOT NULL,
	[ServerRoleDesc] [varchar](50) NOT NULL,
 CONSTRAINT [PK_LU_ServerRole] PRIMARY KEY CLUSTERED 
(
	[ServerRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


